In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Fraud_check.csv')
df.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [3]:
#renaming the columns
df.rename(columns={'Marital.Status':'Marital_Status','Taxable.Income':'Taxable_Income',
                      'City.Population':'City_Population','Work.Experience':'Work_Experience'},inplace=True)
df.head()

Undergrad Marital_Status  Taxable_Income  City_Population  Work_Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [4]:
#converting independent categorical variable  to numerial columns
df=pd.get_dummies(df,drop_first=True)
df.head()

Taxable_Income  City_Population  Work_Experience  Undergrad_YES  \
0           68833            50047               10              0   
1           33700           134075               18              1   
2           36925           160205               30              0   
3           50190           193264               15              1   
4           81002            27533               28              0   

   Marital_Status_Married  Marital_Status_Single  Urban_YES  
0                       0                      1          1  
1                       0                      0          1  
2                       1                      0          1  
3                       0                      1          1  
4                       1                      0          0

In [5]:
a=pd.Series(df['Taxable_Income'])

In [6]:
# If income is less than 30000 label is good else risky 
lst=[]
for i in a:
    x='Good' if i<=30000 else 'Risky'
    lst.append(x)
print(lst)

['Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Good', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Good', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Good', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Good', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Good', 'Good', 'Risky', 'Good', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Risky', 'Good', 'Risky', 'Risky', 'Risky'

In [7]:
a=pd.DataFrame(lst)

In [8]:
df['Tax_Inc']=a
df.head()

Taxable_Income  City_Population  Work_Experience  Undergrad_YES  \
0           68833            50047               10              0   
1           33700           134075               18              1   
2           36925           160205               30              0   
3           50190           193264               15              1   
4           81002            27533               28              0   

   Marital_Status_Married  Marital_Status_Single  Urban_YES Tax_Inc  
0                       0                      1          1   Risky  
1                       0                      0          1   Risky  
2                       1                      0          1   Risky  
3                       0                      1          1   Risky  
4                       1                      0          0   Risky

In [9]:
df.columns

Index(['Taxable_Income', 'City_Population', 'Work_Experience', 'Undergrad_YES',
       'Marital_Status_Married', 'Marital_Status_Single', 'Urban_YES',
       'Tax_Inc'],
      dtype='object')

In [10]:
# encoding target variable
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Tax_Inc']=le.fit_transform(df['Tax_Inc'])
df.head()

Taxable_Income  City_Population  Work_Experience  Undergrad_YES  \
0           68833            50047               10              0   
1           33700           134075               18              1   
2           36925           160205               30              0   
3           50190           193264               15              1   
4           81002            27533               28              0   

   Marital_Status_Married  Marital_Status_Single  Urban_YES  Tax_Inc  
0                       0                      1          1        1  
1                       0                      0          1        1  
2                       1                      0          1        1  
3                       0                      1          1        1  
4                       1                      0          0        1

In [11]:
#Normalizing
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
df=mm.fit_transform(df)

In [12]:
df

array([[0.6564676 , 0.13947207, 0.33333333, ..., 1.        , 1.        ,
        1.        ],
       [0.26442823, 0.62239438, 0.6       , ..., 0.        , 1.        ,
        1.        ],
       [0.3004151 , 0.77256766, 1.        , ..., 0.        , 1.        ,
        1.        ],
       ...,
       [0.41656624, 0.73723987, 0.        , ..., 0.        , 1.        ,
        1.        ],
       [0.98853999, 0.88680969, 0.56666667, ..., 0.        , 0.        ,
        1.        ],
       [0.96540796, 0.76068253, 0.53333333, ..., 0.        , 0.        ,
        1.        ]])

In [13]:
# again converting to dataframe
df=pd.DataFrame(df,columns=['Taxable_Income', 'City_Population', 'Work_Experience', 'Undergrad_YES',
       'Marital_Status_Married', 'Marital_Status_Single', 'Urban_YES',
       'Tax_Inc'])

In [14]:
df.head()

Taxable_Income  City_Population  Work_Experience  Undergrad_YES  \
0        0.656468         0.139472         0.333333            0.0   
1        0.264428         0.622394         0.600000            1.0   
2        0.300415         0.772568         1.000000            0.0   
3        0.448436         0.962563         0.500000            1.0   
4        0.792258         0.010081         0.933333            0.0   

   Marital_Status_Married  Marital_Status_Single  Urban_YES  Tax_Inc  
0                     0.0                    1.0        1.0      1.0  
1                     0.0                    0.0        1.0      1.0  
2                     1.0                    0.0        1.0      1.0  
3                     0.0                    1.0        1.0      1.0  
4                     1.0                    0.0        0.0      1.0

In [16]:
df=df.drop(columns=['Taxable_Income'],axis=1)
df.head()

City_Population  Work_Experience  Undergrad_YES  Marital_Status_Married  \
0         0.139472         0.333333            0.0                     0.0   
1         0.622394         0.600000            1.0                     0.0   
2         0.772568         1.000000            0.0                     1.0   
3         0.962563         0.500000            1.0                     0.0   
4         0.010081         0.933333            0.0                     1.0   

   Marital_Status_Single  Urban_YES  Tax_Inc  
0                    1.0        1.0      1.0  
1                    0.0        1.0      1.0  
2                    0.0        1.0      1.0  
3                    1.0        1.0      1.0  
4                    0.0        0.0      1.0

In [17]:
#X&y
X=df.drop(columns=['Tax_Inc'],axis=1)
y=df['Tax_Inc']

In [19]:
# Splitting data into training and testing data set
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=40)

In [20]:
#import classifier
from sklearn.ensemble import RandomForestClassifier

In [21]:
help(RandomForestClassifier)

Help on class RandomForestClassifier in module sklearn.ensemble._forest:

class RandomForestClassifier(ForestClassifier)
 |  RandomForestClassifier(n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)
 |  
 |  A random forest classifier.
 |  
 |  A random forest is a meta estimator that fits a number of decision tree
 |  classifiers on various sub-samples of the dataset and uses averaging to
 |  improve the predictive accuracy and control over-fitting.
 |  The sub-sample size is controlled with the `max_samples` parameter if
 |  `bootstrap=True` (default), otherwise the whole dataset is used to build
 |  each tree.
 |  
 |  Read more in the :ref:`User Guide <forest>`.
 |  
 |  P

In [47]:
model=RandomForestClassifier(n_estimators=100,max_features=3,random_state=100)

In [48]:
#fit the model
model.fit(X_train,y_train)

RandomForestClassifier(max_features=3, random_state=100)

In [49]:
ypred=model.predict(X_test)

In [50]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ypred,y_test)

array([[ 0,  5],
       [28, 87]], dtype=int64)

In [51]:
#train Accuracy
model.score(X_train,y_train)  # by default parameter 100% accuracy as max_depth=None

1.0

In [52]:
#test Accuracy
model.score(X_test,y_test)

0.725

In [53]:
# important features
model.feature_importances_

array([0.51446684, 0.32229958, 0.04083847, 0.03857824, 0.03143995,
       0.05237693])

In [56]:
# grid Search cv
from sklearn.model_selection import GridSearchCV
param_grid={'n_estimators':[30,60,100,150,250,500],'max_features':[2,3,4]}
grid=GridSearchCV(estimator=RandomForestClassifier(),param_grid=param_grid,cv=5,scoring='accuracy')
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_features': [2, 3, 4],
                         'n_estimators': [30, 60, 100, 150, 250, 500]},
             scoring='accuracy')

# problem 2

In [63]:
company_data=pd.read_csv('Company_Data.csv')
company_data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [64]:
#describing
company_data.describe()

Sales   CompPrice      Income  Advertising  Population  \
count  400.000000  400.000000  400.000000   400.000000  400.000000   
mean     7.496325  124.975000   68.657500     6.635000  264.840000   
std      2.824115   15.334512   27.986037     6.650364  147.376436   
min      0.000000   77.000000   21.000000     0.000000   10.000000   
25%      5.390000  115.000000   42.750000     0.000000  139.000000   
50%      7.490000  125.000000   69.000000     5.000000  272.000000   
75%      9.320000  135.000000   91.000000    12.000000  398.500000   
max     16.270000  175.000000  120.000000    29.000000  509.000000   

            Price         Age   Education  
count  400.000000  400.000000  400.000000  
mean   115.795000   53.322500   13.900000  
std     23.676664   16.200297    2.620528  
min     24.000000   25.000000   10.000000  
25%    100.000000   39.750000   12.000000  
50%    117.000000   54.500000   14.000000  
75%    131.000000   66.000000   16.000000  
max    191.000000   80.000000   18.000000

In [65]:
#checking for missing value
company_data.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [66]:
company_data=pd.get_dummies(company_data,drop_first=True)

In [67]:
company_data.head()

Sales  CompPrice  Income  Advertising  Population  Price  Age  Education  \
0   9.50        138      73           11         276    120   42         17   
1  11.22        111      48           16         260     83   65         10   
2  10.06        113      35           10         269     80   59         12   
3   7.40        117     100            4         466     97   55         14   
4   4.15        141      64            3         340    128   38         13   

   ShelveLoc_Good  ShelveLoc_Medium  Urban_Yes  US_Yes  
0               0                 0          1       1  
1               1                 0          1       1  
2               0                 1          1       1  
3               0                 1          1       1  
4               0                 0          1       0

In [69]:
X=company_data.drop(columns=['Sales'],axis=1)
y=company_data['Sales']

In [70]:
# Splitting data into training and testing data set
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=40)

In [73]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=100,random_state = 42)
rf.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [74]:
rf.score(X_train,y_train)  #train rsquare value

0.9581423979937621

In [75]:
rf.score(X_test,y_test)    #test rsquare value

0.6340838107898713